# Generated by Django 4.0.5 on 2022-06-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0012_auto_20210531_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='dob',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
