# Generated by Django 4.0.5 on 2022-06-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0013_alter_signup_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='answered',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='follower',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='following',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='que_asked',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
