# Generated by Django 4.0.5 on 2022-06-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0017_questions_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='usr_img',
            field=models.ImageField(default='static/a.jpg', upload_to='static/img'),
        ),
    ]
