# Generated by Django 4.0.5 on 2022-06-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0018_signup_usr_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='usr_img',
            field=models.ImageField(default='static/a.jpg', upload_to='./study/static/img'),
        ),
    ]
