# Generated by Django 4.0.5 on 2022-06-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0020_alter_signup_usr_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blogc',
            new_name='blog_c',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='blog',
            name='user_id',
            field=models.IntegerField(default=1, max_length=200, null=True),
        ),
    ]
