# Generated by Django 4.0.5 on 2022-06-21 18:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0021_rename_blogc_blog_blog_c_rename_user_blog_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_c',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
