# Generated by Django 4.0.5 on 2022-06-21 20:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0022_alter_blog_blog_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='ans',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='que',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
