# Generated by Django 4.0.5 on 2022-06-23 10:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0023_alter_questions_ans_alter_questions_que'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_comment',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
